# Generated by Django 5.2.17 on 2026-09-17 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('HAVE_ROOM', 'I Have a Room / Flat (Need Roommate)'), ('NEED_ROOM', 'I Need a Room / Looking to Team Up')], default='NEED_ROOM', max_length=15)),
                ('title', models.CharField(help_text='e.g. 2nd Year DU Student looking for flatmate in Kamla Nagar', max_length=200)),
                ('target_college', models.CharField(help_text='University or College you attend', max_length=200)),
                ('target_city', models.CharField(default='New Delhi', max_length=100)),
                ('target_locality', models.CharField(help_text='Preferred locality or area', max_length=150)),
                ('budget_per_month', models.DecimalField(decimal_places=2, help_text='Max monthly budget per person in ₹', max_digits=10)),
                ('gender_preference', models.CharField(choices=[('MALE', 'Male Roommates Only'), ('FEMALE', 'Female Roommates Only'), ('ANY', 'Any Gender Welcome')], default='MALE', max_length=10)),
                ('occupancy_type', models.CharField(choices=[('SHARED_ROOM', 'Twin Sharing in 1 Room'), ('PRIVATE_ROOM', 'Private Bedroom in Shared Flat'), ('ANY', 'Open to Either')], default='SHARED_ROOM', max_length=15)),
                ('dietary_preference', models.CharField(choices=[('VEG', 'Vegetarian Only'), ('NON_VEG', 'Non-Vegetarian Friendly'), ('EGGETARIAN', 'Eggetarian'), ('ANY', 'No Dietary Preference')], default='ANY', max_length=15)),
                ('smoking_habit', models.CharField(choices=[('NON_SMOKER', 'Strictly Non-Smoker'), ('BALCONY', 'Balcony / Outdoor Only'), ('SMOKER', 'Smoker Friendly')], default='NON_SMOKER', max_length=15)),
                ('sleep_schedule', models.CharField(choices=[('EARLY_BIRD', 'Early Bird (Up before 7 AM)'), ('NIGHT_OWL', 'Night Owl (Active past midnight)'), ('FLEXIBLE', 'Flexible Schedule')], default='FLEXIBLE', max_length=15)),
                ('study_vibe', models.CharField(choices=[('QUIET', 'Quiet & Study Focused'), ('BALANCED', 'Balanced (Study & Hangouts)'), ('SOCIAL', 'Social & Friendly')], default='BALANCED', max_length=15)),
                ('about_me', models.TextField(help_text='Introduce your course, year, lifestyle, and preferences in a flatmate')),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=15)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
