# Generated by Django 5.2.17 on 2026-09-17 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon_class', models.CharField(default='bi bi-check-circle', help_text='Bootstrap Icon class, e.g., bi bi-wifi', max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('property_type', models.CharField(choices=[('HOSTEL', 'Student Hostel'), ('PG', 'Paying Guest (PG)'), ('FLAT', 'Shared Student Flat'), ('ROOM', 'Private Room')], default='PG', max_length=15)),
                ('gender_preference', models.CharField(choices=[('BOYS', 'Boys Only'), ('GIRLS', 'Girls Only'), ('COED', 'Co-Ed / Unisex')], default='BOYS', max_length=10)),
                ('room_sharing', models.CharField(choices=[('SINGLE', 'Single Occupancy (1 Bed)'), ('DOUBLE', 'Double Sharing (2 Beds)'), ('TRIPLE', 'Triple Sharing (3 Beds)'), ('FOUR_PLUS', '4+ Sharing'), ('FULL_FLAT', 'Entire Apartment / Flat')], default='DOUBLE', max_length=15)),
                ('rent_per_month', models.DecimalField(decimal_places=2, help_text='Monthly rent per student in ₹', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, help_text='Refundable deposit in ₹', max_digits=10)),
                ('maintenance_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly maintenance in ₹ (0 if included)', max_digits=8)),
                ('notice_period_days', models.PositiveIntegerField(default=30)),
                ('food_facility', models.CharField(choices=[('INCLUDED_3X', 'All 3 Meals Included (Breakfast, Lunch, Dinner)'), ('INCLUDED_2X', '2 Meals Included (Breakfast & Dinner)'), ('BREAKFAST_ONLY', 'Breakfast Only Included'), ('MESS_AVAILABLE_EXTRA', 'Mess Available at Extra Charge'), ('SELF_COOKING', 'Self-Cooking Allowed / Kitchen Access'), ('NO_FOOD', 'No Food Facility')], default='INCLUDED_2X', max_length=25)),
                ('food_type', models.CharField(choices=[('VEG_ONLY', 'Pure Vegetarian'), ('VEG_NONVEG', 'Veg & Non-Veg Available'), ('JAIN_AVAILABLE', 'Jain Food Available'), ('NA', 'Not Applicable / Self Cook')], default='VEG_NONVEG', max_length=20)),
                ('curfew_time', models.CharField(default='10:30 PM', help_text='e.g. 10:00 PM, 11:00 PM, 24x7 Entry', max_length=50)),
                ('address', models.TextField()),
                ('locality', models.CharField(help_text='e.g. North Campus, Koramangala, Kothrud', max_length=150)),
                ('city', models.CharField(default='New Delhi', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('nearby_college', models.CharField(help_text='Primary nearby university/college', max_length=200)),
                ('distance_to_college_km', models.DecimalField(decimal_places=1, default=0.5, help_text='Distance in KM', max_digits=4)),
                ('nearest_metro_bus', models.CharField(blank=True, help_text='e.g. GTB Nagar Metro Station (300m)', max_length=150)),
                ('description', models.TextField()),
                ('house_rules', models.TextField(blank=True, default='1. Gate closes at designated curfew time.\n2. Outside visitors permitted in lounge area.\n3. Maintain cleanliness in shared spaces.\n4. No smoking or alcohol allowed on premises.')),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=15)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='hostels/')),
                ('is_verified', models.BooleanField(default=True, help_text='Verified zero-brokerage property')),
                ('zero_brokerage_guarantee', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='listings', to='listings.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostels/gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='listings.hostellisting')),
            ],
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('BROKER_FOUND', 'Demanding Brokerage Fee / Broker Posing as Owner'), ('FAKE_PHOTOS', 'Fake Photos or Misleading Room Description'), ('WRONG_PRICE', 'Price Quoted Differently from Portal'), ('UNAVAILABLE', 'Room Already Occupied / Unavailable'), ('SAFETY_ISSUE', 'Safety or Harassment Concern'), ('OTHER', 'Other Violation')], max_length=30)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.hostellisting')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('cleanliness_rating', models.PositiveSmallIntegerField(default=5)),
                ('food_rating', models.PositiveSmallIntegerField(default=5)),
                ('safety_rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.hostellisting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning (09:00 AM - 12:00 PM)'), ('AFTERNOON', 'Afternoon (12:00 PM - 04:00 PM)'), ('EVENING', 'Evening (04:00 PM - 07:30 PM)')], default='EVENING', max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Owner Confirmation'), ('ACCEPTED', 'Visit Confirmed'), ('DECLINED', 'Declined'), ('COMPLETED', 'Visit Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='listings.hostellisting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.hostellisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
