# Generated by Django 5.2.17 on 2026-09-17 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student / Room Seeker'), ('OWNER', 'Hostel / PG Owner')], default='STUDENT', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('college_name', models.CharField(blank=True, help_text='e.g. Delhi University, IIT Bombay, Christ University', max_length=200)),
                ('course', models.CharField(blank=True, help_text='e.g. B.Tech Computer Science, MBA, B.Com', max_length=100)),
                ('year_of_study', models.CharField(blank=True, help_text='e.g. 1st Year, 2nd Year, Final Year', max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Brief introduction about yourself')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_verified_student', models.BooleanField(default=False, help_text='Verified via student ID card')),
                ('is_verified_owner', models.BooleanField(default=False, help_text='Verified property ownership')),
                ('id_card_proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
